-- generated by pipeline/seed.py at 2026-09-26 18:23:06 UTC
INSERT OR REPLACE INTO releases (dataset, label, source_index_url, latest_vintage, checked_at, stale) VALUES
('cps-asec', 'CPS ASEC public-use files (new-format CSV)', 'https://www2.census.gov/programs-surveys/cps/datasets/', '2026', '2026-09-26 18:23:06', 0),
('scf', 'Survey of Consumer Finances', 'https://www.federalreserve.gov/econres/scfindex.htm', '2022', '2026-09-26 18:23:06', 0),
('oecd-idd', 'OECD Income Distribution Database (DF_IDD)', 'https://sdmx.oecd.org/public/rest/v1/data/OECD.WISE.INE,DSD_WISE_IDD@DF_IDD/USA.A.PR_INC_DISP._Z.PT_POP._T.METH2012.D_CUR.PL_50', '2025', '2026-09-26 18:23:06', 0);
