export interface WageTheftSeedRecord {
  case_id: string;
  source_agency: string;
  respondent_legal_name: string;
  trade_name: string;
  address: string;
  city: string;
  state: string;
  zip_code: string;
  naics_code: string;
  industry_description: string;
  violation_type: string;
  back_wages_recovered: number;
  civil_penalties_assessed: number;
  workers_affected: number;
  repeat_violator: number;
  status: string;
  findings_date: string;
  settlement_amount: number;
  description: string;
}

export const WAGE_THEFT_SEED_DATA: WageTheftSeedRecord[] = [
  {
    case_id: "WHD-MN-1892014",
    source_agency: "US_DOL_WHD",
    respondent_legal_name: "DOMINIUM MANAGEMENT SERVICES LLC",
    trade_name: "Dominium",
    address: "2905 Northwest Blvd Ste 150",
    city: "Plymouth",
    state: "MN",
    zip_code: "55441",
    naics_code: "531311",
    industry_description: "Residential Property Managers",
    violation_type: "FLSA_OVERTIME",
    back_wages_recovered: 84520.00,
    civil_penalties_assessed: 12400.00,
    workers_affected: 38,
    repeat_violator: 1,
    status: "SETTLEMENT_REACHED",
    findings_date: "2023-04-12",
    settlement_amount: 96920.00,
    description: "Failed to include on-call stipends and bonuses into regular rate when computing overtime for multi-site apartment maintenance staff."
  },
  {
    case_id: "MNDLI-WH-2022-049",
    source_agency: "MN_DLI",
    respondent_legal_name: "PROPERTY SOLUTIONS & SERVICES LLC",
    trade_name: "PSS Living",
    address: "111 3rd Ave S Ste 220",
    city: "Minneapolis",
    state: "MN",
    zip_code: "55401",
    naics_code: "531110",
    industry_description: "Lessors of Residential Buildings",
    violation_type: "UNPAID_HOURS",
    back_wages_recovered: 62400.00,
    civil_penalties_assessed: 15000.00,
    workers_affected: 24,
    repeat_violator: 0,
    status: "CONSENT_DECREE",
    findings_date: "2022-11-18",
    settlement_amount: 77400.00,
    description: "Unlawful wage deductions for resident caretaker apartment units below statutory minimum wage in violation of Minn. Stat. § 177.24."
  },
  {
    case_id: "MPLS-LS-2023-0082",
    source_agency: "MINNEAPOLIS_CIVIL_RIGHTS",
    respondent_legal_name: "IPG LIVING MANAGEMENT LLC",
    trade_name: "Fitterer Properties",
    address: "310 E 38th St Ste 210",
    city: "Minneapolis",
    state: "MN",
    zip_code: "55409",
    naics_code: "531311",
    industry_description: "Residential Property Management",
    violation_type: "MINIMUM_WAGE",
    back_wages_recovered: 41250.00,
    civil_penalties_assessed: 8500.00,
    workers_affected: 14,
    repeat_violator: 1,
    status: "VIOLATION_CONFIRMED",
    findings_date: "2023-08-30",
    settlement_amount: 49750.00,
    description: "Misclassified building janitors as independent contractors; failed to pay Minneapolis Municipal Minimum Wage and Sick & Safe Time."
  },
  {
    case_id: "WHD-MN-1945112",
    source_agency: "US_DOL_WHD",
    respondent_legal_name: "TWIN CITIES RESIDENTIAL CLEANING & MAINTENANCE INC",
    trade_name: "Metro Caretakers",
    address: "1420 11th Ave S",
    city: "Minneapolis",
    state: "MN",
    zip_code: "55404",
    naics_code: "561720",
    industry_description: "Janitorial Services",
    violation_type: "FLSA_OVERTIME",
    back_wages_recovered: 118400.00,
    civil_penalties_assessed: 22000.00,
    workers_affected: 52,
    repeat_violator: 1,
    status: "JUDGMENT_ENTERED",
    findings_date: "2024-02-14",
    settlement_amount: 140400.00,
    description: "Off-the-clock weekend emergency maintenance calls and alteration of electronic timecards for residential turnover cleaning crews."
  },
  {
    case_id: "MNDLI-WH-2023-102",
    source_agency: "MN_DLI",
    respondent_legal_name: "TIMBERLAND PROPERTY MANAGEMENT INC",
    trade_name: "Timberland Partners",
    address: "8500 Normandale Lake Blvd Ste 600",
    city: "Bloomington",
    state: "MN",
    zip_code: "55437",
    naics_code: "531311",
    industry_description: "Residential Property Managers",
    violation_type: "UNPAID_HOURS",
    back_wages_recovered: 35800.00,
    civil_penalties_assessed: 7500.00,
    workers_affected: 19,
    repeat_violator: 0,
    status: "SETTLEMENT_REACHED",
    findings_date: "2023-10-05",
    settlement_amount: 43300.00,
    description: "Failed to compensate technicians for travel time between properties in Hennepin and Ramsey counties under Minn. Rule 5200.0120."
  },
  {
    case_id: "STP-HREEO-2022-019",
    source_agency: "STPAUL_HREEO",
    respondent_legal_name: "SUMMIT RESIDENTIAL SERVICES LLC",
    trade_name: "Summit Property Management",
    address: "455 Wabasha St N",
    city: "Saint Paul",
    state: "MN",
    zip_code: "55102",
    naics_code: "531311",
    industry_description: "Residential Property Management",
    violation_type: "MINIMUM_WAGE",
    back_wages_recovered: 28900.00,
    civil_penalties_assessed: 5000.00,
    workers_affected: 11,
    repeat_violator: 0,
    status: "SETTLEMENT_REACHED",
    findings_date: "2022-07-22",
    settlement_amount: 33900.00,
    description: "Saint Paul Minimum Wage Ordinance violations for apartment building cleaners and security desk attendants."
  },
  {
    case_id: "MNAG-WT-2023-014",
    source_agency: "COURT_JUDGMENT",
    respondent_legal_name: "NORTH STAR CONTRACTING & DRYWALL LLC",
    trade_name: "North Star Residential",
    address: "6200 Brooklyn Blvd",
    city: "Brooklyn Center",
    state: "MN",
    zip_code: "55429",
    naics_code: "238310",
    industry_description: "Drywall and Insulation Contractors",
    violation_type: "MISCLASSIFICATION",
    back_wages_recovered: 312000.00,
    civil_penalties_assessed: 65000.00,
    workers_affected: 86,
    repeat_violator: 1,
    status: "JUDGMENT_ENTERED",
    findings_date: "2023-12-11",
    settlement_amount: 377000.00,
    description: "Ramsey County District Court consent judgment: systemic misclassification of multi-family renovation workers as independent contractors."
  },
  {
    case_id: "WHD-MN-2001884",
    source_agency: "US_DOL_WHD",
    respondent_legal_name: "KLEINMAN COMMERCIAL REAL ESTATE & HOUSING LLC",
    trade_name: "Kleinman Realty Co",
    address: "5201 E River Rd Ste 308",
    city: "Minneapolis",
    state: "MN",
    zip_code: "55421",
    naics_code: "531311",
    industry_description: "Residential Property Managers",
    violation_type: "FLSA_OVERTIME",
    back_wages_recovered: 19450.00,
    civil_penalties_assessed: 3200.00,
    workers_affected: 8,
    repeat_violator: 0,
    status: "VIOLATION_CONFIRMED",
    findings_date: "2024-01-19",
    settlement_amount: 22650.00,
    description: "Improper comp-time bank calculations in lieu of 1.5x cash overtime for groundskeepers and building engineers."
  },
  {
    case_id: "WHD-MN-2023-0189",
    source_agency: "US_DOL_WHD",
    respondent_legal_name: "METRO MULTIFAMILY PAINTERS LLC",
    trade_name: "Metro Pro Painters",
    address: "780 University Ave W",
    city: "Saint Paul",
    state: "MN",
    zip_code: "55104",
    naics_code: "238320",
    industry_description: "Painting and Wall Covering Contractors",
    violation_type: "MISCLASSIFICATION",
    back_wages_recovered: 88200.00,
    civil_penalties_assessed: 18500.00,
    workers_affected: 31,
    repeat_violator: 1,
    status: "CONSENT_DECREE",
    findings_date: "2023-09-15",
    settlement_amount: 106700.00,
    description: "Misclassified turnover painters as 1099 independent contractors across 14 multi-family apartment communities; denied overtime compensation."
  },
  {
    case_id: "MNDLI-WH-2024-031",
    source_agency: "MN_DLI",
    respondent_legal_name: "MIDWEST RESIDENTIAL JANITORIAL SERVICES LLC",
    trade_name: "CleanStart Properties",
    address: "2412 Nicollet Ave",
    city: "Minneapolis",
    state: "MN",
    zip_code: "55404",
    naics_code: "561720",
    industry_description: "Janitorial Services",
    violation_type: "MINIMUM_WAGE",
    back_wages_recovered: 34600.00,
    civil_penalties_assessed: 8000.00,
    workers_affected: 16,
    repeat_violator: 0,
    status: "SETTLEMENT_REACHED",
    findings_date: "2024-03-21",
    settlement_amount: 42600.00,
    description: "Retaliation and failure to pay accrued Earned Sick and Safe Time (ESST) to residential turnover cleaning technicians."
  },
  {
    case_id: "MPLS-LS-2024-0012",
    source_agency: "MINNEAPOLIS_CIVIL_RIGHTS",
    respondent_legal_name: "CEDAR RIVERSIDE CARETAKER COLLECTIVE LLC",
    trade_name: "West Bank Living",
    address: "1600 S 6th St",
    city: "Minneapolis",
    state: "MN",
    zip_code: "55454",
    naics_code: "531311",
    industry_description: "Residential Property Management",
    violation_type: "UNPAID_HOURS",
    back_wages_recovered: 54000.00,
    civil_penalties_assessed: 11200.00,
    workers_affected: 18,
    repeat_violator: 1,
    status: "VIOLATION_CONFIRMED",
    findings_date: "2024-05-10",
    settlement_amount: 65200.00,
    description: "Paid building caretakers with rent fee concessions valued well beneath Minneapolis municipal minimum wage for 35+ hours/week."
  },
  {
    case_id: "WHD-MN-2024-1102",
    source_agency: "US_DOL_WHD",
    respondent_legal_name: "HENNEPIN MULTIFAMILY ROOFING & SHEET METAL INC",
    trade_name: "Twin Cities Exterior Pros",
    address: "5400 Winnetka Ave N",
    city: "New Hope",
    state: "MN",
    zip_code: "55428",
    naics_code: "238160",
    industry_description: "Roofing Contractors",
    violation_type: "PREVAILING_WAGE",
    back_wages_recovered: 145000.00,
    civil_penalties_assessed: 29000.00,
    workers_affected: 42,
    repeat_violator: 1,
    status: "JUDGMENT_ENTERED",
    findings_date: "2024-06-18",
    settlement_amount: 174000.00,
    description: "Falsification of certified payroll records and kickback demands on prevailing wage Davis-Bacon subsidized residential rehabilitation contracts."
  },
  {
    case_id: "MNAG-WT-2024-009",
    source_agency: "COURT_JUDGMENT",
    respondent_legal_name: "LAKES AREA ASSET MANAGEMENT LLC",
    trade_name: "Lakes Property Solutions",
    address: "12400 Wayzata Blvd",
    city: "Minnetonka",
    state: "MN",
    zip_code: "55305",
    naics_code: "531311",
    industry_description: "Residential Property Management",
    violation_type: "DEDUCTION_THEFT",
    back_wages_recovered: 26400.00,
    civil_penalties_assessed: 4800.00,
    workers_affected: 12,
    repeat_violator: 0,
    status: "CONSENT_DECREE",
    findings_date: "2024-02-28",
    settlement_amount: 31200.00,
    description: "Unlawful deductions from caretakers' final paychecks for alleged tenant damages and carpet cleaning supplies."
  },
  {
    case_id: "WHD-MN-2024-0455",
    source_agency: "US_DOL_WHD",
    respondent_legal_name: "ARROWHEAD APARTMENT SERVICES LLC",
    trade_name: "Arrowhead Turnover Solutions",
    address: "1821 University Ave W",
    city: "Saint Paul",
    state: "MN",
    zip_code: "55104",
    naics_code: "561790",
    industry_description: "Other Services to Buildings and Dwellings",
    violation_type: "FLSA_OVERTIME",
    back_wages_recovered: 67500.00,
    civil_penalties_assessed: 13400.00,
    workers_affected: 26,
    repeat_violator: 1,
    status: "SETTLEMENT_REACHED",
    findings_date: "2024-04-04",
    settlement_amount: 80900.00,
    description: "Uncompensated mandatory on-call response time for plumbing, heating, and turnover emergencies across 22 rental buildings."
  }
];
